sitename: Longterm eCommerce Strategy | Downshift Labs
tagline: Organic marketing, content canonicalization and user experience

production_url: http://downshiftlabs.com
url: http://downshiftlabs.com

safe: false
baseurl: /

markdown: rdiscount
pygments: true
